using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos;
using Content.Shared.Temperature;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using static Content.Shared.Atmos.Components.GasAnalyzerComponent;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client.Atmos.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class DebugGasSpawnerWindow : DefaultWindow
    {
        public DebugGasSpawnerWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void Populate(List<string> gasNames)
        {
            GasSelectionOptionButton.Clear();
            for (var i = 0; i < gasNames.Count; i++)
            {
                GasSelectionOptionButton.AddItem(gasNames[i], i);
            }

            GasSelectionOptionButton.SelectId(0); // По умолчанию первый газ
        }
    }
}
